### ISSUE TITLE
half acquisition mode axis feature

### ISSUE THREAD

**Issue by toby-bond** [sgasilov/ez_ufo#1]
When images are stitched in half acquisition mode, the image dimensions can vary from scan to scan if the stitch point is different. The resulting stitched scans will always have the axis of rotation at the center of the image, so a useful feature would be to bypass the axis search/set options in ezufo and simply use the image midpoint as the axis. This would save having to go back and open each image to find the stitched dimensions and would allow for easy batch reconstruction of stitched half acquisition mode scans.

**Comment by sgasilov** [comment]
done
